[profile.default]
test = 'test/solidity'
solc_version = '0.8.29'
evm_version = 'cancun'
auto_detect_solc = false
optimizer = true
optimizer_runs = 1000000
# use a known address with a balance so ZkEVM scripts work
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea73'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea73'
out = 'out'
fs_permissions = [
  { access = "read", path = "./deployments/" },
  { access = "read", path = "./config/" },
  { access = "read-write", path = "./test/logs/" },
  { access = "read", path = "./zkout/" },
]
ffi = true
libs = ["node_modules", "lib"]
cache = true

[profile.zksync]
solc_version = '0.8.26'
zksolc = '1.5.15'
test = "notest"
script = "script/deploy/zksync"
cache_path = "./zkcache"
out = "out/zksync"

[rpc_endpoints]
mainnet = "${ETH_NODE_URI_MAINNET}"
abstract = "${ETH_NODE_URI_ABSTRACT}"
apechain = "${ETH_NODE_URI_APECHAIN}"
arbitrum = "${ETH_NODE_URI_ARBITRUM}"
aurora = "${ETH_NODE_URI_AURORA}"
avalanche = "${ETH_NODE_URI_AVALANCHE}"
base = "${ETH_NODE_URI_BASE}"
berachain = "${ETH_NODE_URI_BERACHAIN}"
blast = "${ETH_NODE_URI_BLAST}"
boba = "${ETH_NODE_URI_BOBA}"
bob = "${ETH_NODE_URI_BOB}"
bsc = "${ETH_NODE_URI_BSC}"
celo = "${ETH_NODE_URI_CELO}"
corn = "${ETH_NODE_URI_CORN}"
cronos = "${ETH_NODE_URI_CRONOS}"
evmos = "${ETH_NODE_URI_EVMOS}"
fantom = "${ETH_NODE_URI_FANTOM}"
flare = "${ETH_NODE_URI_FLARE}"
fraxtal = "${ETH_NODE_URI_FRAXTAL}"
fuse = "${ETH_NODE_URI_FUSE}"
harmony = "${ETH_NODE_URI_HARMONY}"
hyperevm = "${ETH_NODE_URI_HYPEREVM}"
gnosis = "${ETH_NODE_URI_GNOSIS}"
gravity = "${ETH_NODE_URI_GRAVITY}"
etherlink = "${ETH_NODE_URI_ETHERLINK}"
immutablezkevm = "${ETH_NODE_URI_IMMUTABLEZKEVM}"
ink = "${ETH_NODE_URI_INK}"
kaia = "${ETH_NODE_URI_KAIA}"
katana = "${ETH_NODE_URI_KATANA}"
lens = "${ETH_NODE_URI_LENS}"
linea = "${ETH_NODE_URI_LINEA}"
lisk = "${ETH_NODE_URI_LISK}"
moonbeam = "${ETH_NODE_URI_MOONBEAM}"
moonriver = "${ETH_NODE_URI_MOONRIVER}"
nova = "${ETH_NODE_URI_NOVA}"
mantle = "${ETH_NODE_URI_MANTLE}"
metis = "${ETH_NODE_URI_METIS}"
mode = "${ETH_NODE_URI_MODE}"
nibiru = "${ETH_NODE_URI_NIBIRU}"
okx = "${ETH_NODE_URI_OKX}"
opbnb = "${ETH_NODE_URI_OPBNB}"
optimism = "${ETH_NODE_URI_OPTIMISM}"
plume = "${ETH_NODE_URI_PLUME}"
polygon = "${ETH_NODE_URI_POLYGON}"
polygonzkevm = "${ETH_NODE_URI_POLYGONZKEVM}"
rootstock = "${ETH_NODE_URI_ROOTSTOCK}"
ronin = "${ETH_NODE_URI_RONIN}"
sei = "${ETH_NODE_URI_SEI}"
soneium = "${ETH_NODE_URI_SONEIUM}"
sonic = "${ETH_NODE_URI_SONIC}"
sophon = "${ETH_NODE_URI_SOPHON}"
superposition = "${ETH_NODE_URI_SUPERPOSITION}"
swellchain = "${ETH_NODE_URI_SWELLCHAIN}"
taiko = "${ETH_NODE_URI_TAIKO}"
velas = "${ETH_NODE_URI_VELAS}"
unichain = "${ETH_NODE_URI_UNICHAIN}"
vana = "${ETH_NODE_URI_VANA}"
viction = "${ETH_NODE_URI_VICTION}"
worldchain = "${ETH_NODE_URI_WORLDCHAIN}"
xdc = "${ETH_NODE_URI_XDC}"
xlayer = "${ETH_NODE_URI_XLAYER}"
zksync = "${ETH_NODE_URI_ZKSYNC}"
scroll = "${ETH_NODE_URI_SCROLL}"

# testnets
localanvil = "${ETH_NODE_URI_LOCALANVIL}"

